// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_net_id.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Keep.NetProtocol.Proto {

  /// <summary>Holder for reflection information generated from game_net_id.proto</summary>
  public static partial class GameNetIdReflection {

    #region Descriptor
    /// <summary>File descriptor for game_net_id.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameNetIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFnYW1lX25ldF9pZC5wcm90bxIWS2VlcC5OZXRQcm90b2NvbC5Qcm90bypb",
            "ChBnYW1lX3Jlc3VsdF9jb2RlEg0KCWNvZGVfbm9uZRAAEhUKEWNvZGVfdW5r",
            "b253X2Vycm9yEGQSEQoMY29kZV9zdWNjZXNzEMgBEg4KCWNvZGVfZmFpbBDJ",
            "ASp3Cg9uZXRfc2VydmVyX3R5cGUSEwoPbmV0X3NlcmV2cl9ub25lEAASGgoV",
            "YXZhdGFyX2NyZWF0ZV9uZXdfcmVxEJFOEhwKF2F2YXRhcl9uaWNrbmFtZV9z",
            "ZXRfcmVxEJJOEhUKEGF2YXRhcl9sb2dpbl9yZXEQk04qdwoPbmV0X2NsaWVu",
            "dF90eXBlEhMKD25ldF9jbGllbnRfbm9uZRAAEhoKFWF2YXRhcl9jcmVhdGVf",
            "bmV3X3JlcBCRThIcChdhdmF0YXJfbmlja25hbWVfc2V0X3JlcBCSThIVChBh",
            "dmF0YXJfbG9naW5fcmVwEJNOYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Keep.NetProtocol.Proto.game_result_code), typeof(global::Keep.NetProtocol.Proto.net_server_type), typeof(global::Keep.NetProtocol.Proto.net_client_type), }, null));
    }
    #endregion

  }
  #region Enums
  public enum game_result_code {
    [pbr::OriginalName("code_none")] CodeNone = 0,
    /// <summary>
    /// 未知错误
    /// </summary>
    [pbr::OriginalName("code_unkonw_error")] CodeUnkonwError = 100,
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("code_success")] CodeSuccess = 200,
    /// <summary>
    /// 失败
    /// </summary>
    [pbr::OriginalName("code_fail")] CodeFail = 201,
  }

  public enum net_server_type {
    [pbr::OriginalName("net_serevr_none")] NetSerevrNone = 0,
    [pbr::OriginalName("avatar_create_new_req")] AvatarCreateNewReq = 10001,
    [pbr::OriginalName("avatar_nickname_set_req")] AvatarNicknameSetReq = 10002,
    [pbr::OriginalName("avatar_login_req")] AvatarLoginReq = 10003,
  }

  public enum net_client_type {
    [pbr::OriginalName("net_client_none")] NetClientNone = 0,
    [pbr::OriginalName("avatar_create_new_rep")] AvatarCreateNewRep = 10001,
    [pbr::OriginalName("avatar_nickname_set_rep")] AvatarNicknameSetRep = 10002,
    [pbr::OriginalName("avatar_login_rep")] AvatarLoginRep = 10003,
  }

  #endregion

}

#endregion Designer generated code
